# Generated by Django 4.2.1 on 2023-05-31 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_alter_heatingsettings_is_heating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturearchive',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='temperaturearchive',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
